// Generated by CoffeeScript 2.5.1
import sleep from './sleep.js';

(async() => {
  var n, results;
  n = 0;
  results = [];
  while (++n < 3) {
    console.log(new Date());
    results.push((await sleep(1)));
  }
  return results;
})();

//# sourceMappingURL=sleep_test.js.map
